[MTDSA-6933] - adjusting minimum tax year
hmrc/other-deductions-api pull request #29
Opened 2020-09-10 10:36 UTC by DreamcastKnight

2020-09-10 12:48 UTC, Mbrookesy requested changes

2020-09-10 12:48 UTC, Mbrookesy commented on app/config/AppConfig.scala
> +  val minimumTaxYear = 2022
You need to move the minimumTaxYear from fixed config to the overridable appconfig section.

2020-09-10 12:48 UTC, Mbrookesy commented on it/v1/endpoints/SampleControllerISpec.scala
> + * Copyright 2020 HM Revenue & Customs
Why is there a sample controller here?

2020-09-10 12:48 UTC, Mbrookesy commented on test/v1/controllers/requestParsers/validators/AmendOtherDeductionsValidatorSpec.scala
> +  private val validTaxYear = "201-22"
taxYear is mispelt

2020-09-11 10:54 UTC, james-work-account requested changes
Also `currentTaxYear` isn't used in MtdTaxYearValidation - again I know this wasn't put in by you but it'd be good to take it out just to get rid of the compilation warnings.

2020-09-11 10:54 UTC, james-work-account commented on test/v1/controllers/requestParsers/validators/AmendOtherDeductionsValidatorSpec.scala
>  class AmendOtherDeductionsValidatorSpec @Inject()(implicit appConfig: AppConfig, currentTaxYear: CurrentTaxYear) extends UnitSpec {
I know you didn't change this but the Inject stuff is unnecessary (also remove any unused imports please).

```suggestion
class AmendOtherDeductionsValidatorSpec extends UnitSpec {
```

2020-09-11 16:41 UTC, james-work-account approved these changes

2020-09-11 16:42 UTC, merged